### PR TITLE
Add validate tool

### PR DESCRIPTION
**Pull request by sebastian-nagel**
Add tool to validate WARC/ARC files: verify digests, Content-Length headers, media type syntax, syntax of (parse errors in) HTTP headers. Read the payload to find/trigger errors when decoding transfer or content encoding.

Note: #59 is required to properly verify digests.

```
$> java -cp target/jwarc-*.jar org.netpreserve.jwarc.tools.WarcTool validate

ValidateTool [-h] [-v] filename...

Options:

 -h / --help    show usage message and exit
 -v / --verbose log information about every WARC record to stdout

Exit value is 0 if all WARC files validate, 1 otherwise.
Errors and erroneous WARC records are logged to stderr.

$> java -cp target/jwarc-*.jar org.netpreserve.jwarc.tools.WarcTool validate -v test-resources/org/netpreserve/jwarc/cc.warc.gz 
Validating test-resources/org/netpreserve/jwarc/cc.warc.gz
  offset 0 (length 5392) response application/http;msgtype=response
    http://commoncrawl.org/
    HTTP/1.1 200 OK
    date: 2019-12-10T10:00:01Z
    payload media type: text/html
    payload digest pass
    block digest pass
```

### CODE REVIEW

**Review by ato — COMMENTED** [review]
I like this tool but I wonder if we can integrate the block digest calculation more directly. Making defaultTypes public and then using it to create copies of each record with an injected body wrapper feels like we're jumping through hoops to work around a missing feature that should just be part of the API.

Perhaps we could have a method on WarcReader that enables block digest calculation and then add a `calculatedBlockDigest()` on each WarcRecord you can compare to `blockDigest()`?

**Comment by sebastian-nagel** [comment]
Yes, definitely. I'll update the PR accordingly.

**Comment by ato** [comment]
Thanks. Released as 0.15.0 with a couple of small tweaks. When I tested it I found DigestingMessageBody was producing the wrong digest as it was digesting the unused remaining part of the buffer instead of the bytes that had just been read.

**Comment by sebastian-nagel** [comment]
Thanks!

**Pull request merged**
